export const SEARCH_RESTAURANTS = 'SEARCH_RESTAURANTS';

export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';

export const SET_ERROR = 'SET_ERROR';

export const UNSET_ERROR = 'UNSET_ERROR';
