export const restaurantActions = {
  SEARCH_RESTAURANTS: 'SEARCH_RESTAURANTS',

  LOADING_RESTAURANTS: 'LOADING_RESTAURANTS',
  FETCH_RESTAURANTS: 'FETCH_RESTAURANTS',
  ERROR_RESTAURANTS: 'ERROR_RESTAURANTS',

  LOADING_LOCATION: 'LOADING_LOCATION',
  FETCH_LOCATION: 'FETCH_LOCATION',
  ERROR_LOCATION: 'ERROR_LOCATION',
};
