export const SEARCH_RESTAURANTS = 'SEARCH_RESTAURANTS';

export const LOADING_RESTAURANTS = 'LOADING_RESTAURANTS';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const ERROR_RESTAURANTS = 'ERROR_RESTAURANTS';

export const LOADING_LOCATION = 'LOADING_LOCATION';
export const FETCH_LOCATION = 'FETCH_LOCATION';
export const ERROR_LOCATION = 'ERROR_LOCATION';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const SAVE_FAVORITES = 'SAVE_FAVORITES';
